name: CI for dev

# トリガーの設定
on:
  push:
    branches: [ develop ]

# ジョブの設定（直列に動かしたり並行に動かしたり指定できる）
# 今回はbuildジョブとdeployジョブの2つを設定します
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      # masterブランチをチェックアウト
      - uses: actions/checkout@v3
      # nodeでパッケージをインストール&ビルド
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn export
      # ビルド結果をdeployジョブに渡すためにアップロード
      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: out/

  deploy:
    # ジョブは並行で動くので前後関係の指定が必要
    needs: build

    runs-on: ubuntu-latest

    steps:
      # ビルド結果をダウンロード
      - name: Download build result
        uses: actions/download-artifact@v3
        with:
          name: build
          path: out/
      # S3にアップロード
      - name: Publish to AWS S3
        uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-1'
          FROM_PATH: 'out/'
          DEST_PATH: 's3://${{secrets.AWS_DEV_S3_BUCKET_NAME}}'
      # CloudFrontのキャッシュクリア
      - name: Clear cache in CloudFront
        uses: chetan/invalidate-cloudfront-action@v2.3
        env:
          DISTRIBUTION: ${{ secrets.AWS_DEV_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
